# Generated by Django 5.2.4 on 2025-07-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike', models.CharField(max_length=50)),
                ('amt', models.FloatField()),
                ('transaction', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=100)),
            ],
        ),
    ]
